# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i9lC6XYvkzyl5pjSaNFFbB2LrX2f8bUT
"""

import streamlit as st
import pdfplumber
import openai
import os
from dotenv import load_dotenv

# Load API key from .env
load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")

st.set_page_config(page_title="Free GenAI Resume Assistant", layout="centered")
st.title("🧠 Free GPT-3.5 Resume Assistant")

st.markdown("Upload your resume and paste a job description. This version uses GPT-3.5 and is free if within OpenAI limits.")

# Upload resume
resume_file = st.file_uploader("📄 Upload your resume (PDF only)", type=["pdf"])
job_desc = st.text_area("💼 Paste the job description here")

def extract_text_from_pdf(uploaded_file):
    text = ""
    with pdfplumber.open(uploaded_file) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + "\n"
    return text

def load_prompt_template():
    with open("prompts/resume_prompt.txt", "r") as file:
        return file.read()

def generate_updated_resume(resume_text, job_description):
    prompt_template = load_prompt_template()
    prompt = prompt_template.replace("{{RESUME}}", resume_text).replace("{{JOB_DESCRIPTION}}", job_description)

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7,
        max_tokens=1500
    )
    return response['choices'][0]['message']['content']

if st.button("🔍 Tailor Resume"):
    if not resume_file or not job_desc.strip():
        st.warning("Please upload a resume and paste a job description.")
    else:
        with st.spinner("Rewriting your resume with GPT-3.5..."):
            resume_text = extract_text_from_pdf(resume_file)
            updated_resume = generate_updated_resume(resume_text, job_desc)
            st.subheader("✅ Tailored Resume")
            st.code(updated_resume)
            st.download_button("⬇ Download as .txt", data=updated_resume, file_name="tailored_resume.txt", mime="text/plain")